chore: improve contributing
zitadel/typescript pull request #20
Opened 2023-05-19 14:20 UTC by eliobischof

2023-05-19 18:11 UTC, eliobischof commented on CODE_OF_CONDUCT.md
This file feels arrogant to me and I don't think anybody cares about it :smile:

2023-05-22 14:04 UTC, peintnermax commented on CONTRIBUTING.md
> +- üull requests need approval of a ZITADEL core engineer @zitadel/engineers before merging
```suggestion
- Pull requests need approval of a ZITADEL core engineer @zitadel/engineers before merging
```

2023-05-23 06:39 UTC, peintnermax requested changes
We should backup the current `.env.local` before we overwrite the variables.. Rest works nicely 👍

2023-05-23 16:42 UTC, eliobischof commented
> We should backup the current `.env.local` before we overwrite the variables.. Rest works nicely +1

Automated it https://github.com/zitadel/typescript/pull/20/commits/5748aab4d4b342e6a9d0efe2972343555736f52d

2023-05-24 12:36 UTC, peintnermax approved these changes

2023-05-24 12:37 UTC, merged