test: setup unit and integration tests
zitadel/typescript pull request #25
Opened 2023-06-05 11:03 UTC by eliobischof

2023-06-07 12:21 UTC, peintnermax commented
lets add the output of cypress to `.gitignore`

# cypress
apps/login/cypress/screenshots
apps/login/cypress/videos

2023-06-07 12:59 UTC, peintnermax commented
don't we need a `jest-setup.ts` in apps/login for setting up the testing library `import '@testing-library/jest-dom/extend-expect'` just like in zitadel-react ?

2023-06-07 13:15 UTC, peintnermax requested changes

2023-06-07 13:15 UTC, peintnermax commented on packages/zitadel-server/package.json
> +    "@mocks-server/main": "^4.1.0",
do we need this?

2023-06-08 04:38 UTC, eliobischof commented
> don't we need a `jest-setup.ts` in apps/login for setting up the testing library `import '@testing-library/jest-dom/extend-expect'` just like in zitadel-react ?

We just need the "@testing-library/jest-dom/extend-expect" module loaded before the test suite. That's with the setupFilesAfterEnv property in jest.config.ts.

I fixed it in zitadel-react too.

2023-06-08 04:39 UTC, eliobischof commented
> lets add the output of cypress to `.gitignore`
> 
> ```
> # cypress
> apps/login/cypress/screenshots
> apps/login/cypress/videos
> ```

I removed the whole cypress folder for now.

2023-06-08 04:46 UTC, eliobischof commented on packages/zitadel-server/package.json
> +    "@mocks-server/main": "^4.1.0",
uninstalled it :+1:

2023-06-08 05:00 UTC, eliobischof commented on package.json
> +    "prebuild": "turbo run generate",
right, but the turbo.json is project scoped, right? So it still makes sense to keep the prebuild script in the package.json, for cases you just want to build the zitadel-client. What do you think?

The generate task is already defined as a dependency of the build task in turbo.json.

2023-06-08 05:00 UTC, eliobischof commented on packages/zitadel-client/package.json
> +    "prebuild": "pnpm run generate",
right, but the turbo.json is project scoped, right? So it still makes sense to keep the prebuild script in the package.json, for cases you just want to build the zitadel-client. What do you think?

The generate task is already defined as a dependency of the build task in turbo.json.

2023-06-08 05:02 UTC, eliobischof commented on package.json
> +    "prebuild": "turbo run generate",
The generate task is already defined as a dependency of the build task in turbo.json.

I removed it here :+1:

2023-06-08 07:11 UTC, peintnermax approved these changes

2023-06-08 07:12 UTC, merged